name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master
      - option-a # Added since user is currently working on this branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin

      - name: Build and Deploy
        run: mkdocs gh-pages --force --config-file docs/mkdocs.yml
